### ISSUE TITLE
Module scripts.whitelist is missing

### ISSUE THREAD

**Issue by ThatMorganGuy** [AICatgirls/aichatgirls#10]
C:\Users\mjcar\Downloads\aichatgirls>python aichatgirls.py
Traceback (most recent call last):
  File "C:\Users\mjcar\Downloads\aichatgirls\aichatgirls.py", line 20, in <module>
    from chatCommand import chat_command
  File "C:\Users\mjcar\Downloads\aichatgirls\chatCommand.py", line 3, in <module>
    from scripts.whitelist import Whitelist
ModuleNotFoundError: No module named 'scripts.whitelist'

not sure what im missing, i've moved the whitelist out of a python download and put it in scripts but not sure why its still spitting this out. any helo would be amazing!

**Comment by ThatMorganGuy** [comment]
and how am i connecting this to oodabooda?

**Comment by AICatgirls** [comment]
You should have a C:\Users\mjcar\Downloads\aichatgirls\scripts folder, and in that folder should be the whitelist.py file. I'll try doing a fresh install later today to validate that I still have the steps right, but the error message is basically saying it can't find that file.

Regarding connecting to oobabooga, all it should take is enabling the API. It's possible though that they've changed how the API works. I'll check that out as well and let you know what I find!

**Comment by ThatMorganGuy** [comment]
its there not sure why it doesnt see it though, ended up getting a little ahead but ended up getting this error instead.

C:\Users\mjcar\Downloads\aichatgirls>python aichatgirls.py
Traceback (most recent call last):
  File "C:\Users\mjcar\Downloads\aichatgirls\aichatgirls.py", line 20, in <module>
    from chatCommand import chat_command
  File "C:\Users\mjcar\Downloads\aichatgirls\chatCommand.py", line 3, in <module>
    from scripts.whitelist import Whitelist
ImportError: cannot import name 'Whitelist' from 'scripts.whitelist' (C:\Users\mjcar\Downloads\aichatgirls\scripts\whitelist\__init__.py)

**Comment by AICatgirls** [comment]
I'm not sure what whitelist_init_.py is. Did you just rename the version of whitelist.py that I have here?: [https://github.com/AICatgirls/aichatgirls/blob/main/scripts/whitelist.py](https://github.com/AICatgirls/aichatgirls/blob/main/scripts/whitelist.py)

I still have another 4-5 hours of work before I can really start debugging.

**Comment by ThatMorganGuy** [comment]
i changed the name of the __init__.py thinning it would do anything. but ofc i was incorrect with the workaround

no worries lol I'm in no rush.

**Comment by AICatgirls** [comment]
I just created a new anaconda environment with python 3.8, downloaded the repository to my Downloads folder, installed the requirements, created my .env file with the discord bot token, ran `python aichatgirls.py` and everything worked fine. I'm running Windows 10.

One thing I noticed though, I had a typo in my install instructions which I have just corrected. The command to install requirements should be `pip install -r requirements.txt`, not the `-4` I had in there before. (Though if that were an issue for you you'd be seeing a different error I think.)

I could suggest trying to install again from scratch in a different folder, but without understanding what's causing the problem it might be a waste of time. Any info you can think of that might be relevant to helping me reproduce the problem?

**Comment by ThatMorganGuy** [comment]
hhmmm thats really odd, ill try a fresh start and see if maybe i just goofed a step or not.

**Comment by ThatMorganGuy** [comment]
made a new environment for it on a laptop, not sure what went wrong on my main pc but it seems to work now lol thanks again for the help debugging. no idea why my computer is being goofy with it.

**Comment by AICatgirls** [comment]
@motormonster I'm glad you were able to get it to install. I've been doing some testing this morning with the latest oobabooga and it looks like the API has changed. And I also found a couple defects in my code as well that I've made fixes for, but I don't want to do a release until after end to end tests pass. You could use the forked version of ooba that I have in my repo in the meantime, but I hope to have an updated version of the discord bot out this evening.

**Comment by ThatMorganGuy** [comment]
Yea I found that out with another bot that the api changed for oobabooga, you can go and still use the old api with a few changes to the code.

**Comment by ThatMorganGuy** [comment]
heres a link to get the snapshot of oobabooga with the legacy api

https://github.com/oobabooga/text-generation-webui/issues/4581#issuecomment-1810232103


and heres the comment with the shared.py code that needs to be added.

https://github.com/chrisrude/oobabot/issues/83#issuecomment-1873033346
