### ISSUE TITLE
Add support for Alpaca formatting

### ISSUE THREAD

**Issue by Chris2918** [AICatgirls/aichatgirls#15]
I'm currently using this with [Kunoichi-7B](https://huggingface.co/SanjiWatsuki/Kunoichi-7B) which uses the Alpaca format

However, due to the current prompt format, it often makes up user responses and replies.
Here is what Alpaca formatting usually looks like:

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{prompt}

### Response:"

```

**Comment by AICatgirls** [comment]
Text-generation-webui seems to be automatically applying the Alpaca template behind the scenes. In testing with Kunoichi-7B though I noticed that the stopping strings were being ignored, and in looking at the API it seems like the parameter name for those may have changed.

Please update and try it out, and if you're still experiencing this issue please reopen it.
